Ticket.Web/Ticket.Web/Models/Account/LoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Ticket.Web.Models.Account
{
    public class LoginModel
    {
        [Required(ErrorMessage="Please fill E-mail field")]
        public string Email { get; set; }

        [Required(ErrorMessage="Please fill Password field")]
        public string Password { get; set; }

        public string ReturnUrl { get; set; }
    }
}

Ticket.Web/Ticket.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticket.Web.Filters;
using Ticket.Web.Models.Account;
using WebMatrix.WebData;

namespace Ticket.Web.Controllers
{
    [InitializeSimpleMembership]
    public class AccountController : BaseController
    {
        //
        // GET: /Accounts/
        [AllowAnonymous]
        public ActionResult LogOn()
        {
            return View("LogOn");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult LogOn(LoginModel model)
        {
            if (ModelState.IsValid && WebSecurity.Login(model.Email, model.Password, persistCookie:true))
            {
                return  RedirectToAction("Index", "Home");
            }

            // If we got this far, something failed, redisplay form
            ModelState.AddModelError("", "The user name or password provided is incorrect.");
            return View(model);
        }

      
        public ActionResult LogOff()
        {
            WebSecurity.Logout();

            return RedirectToAction("Index", "Home");
        } 


        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Ticket.Web/Ticket.Web/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticket.Web.DAL.Repository.Model.Administration;
using WebMatrix.WebData;

namespace Ticket.Web.Controllers
{
    public class AdministrationController : BaseController
    {
        //
        // GET: /Administration/

        public ActionResult Users()
        {
            var users = UnitOfWork.AdministrationRepository.GetUsers(UnitOfWork);
            return View("Users", users);
        }

        public ActionResult EditUser(int userId)
        {
            var user = UnitOfWork.AdministrationRepository.GetUser(UnitOfWork, userId);
            return PartialView("_editUserPartial", user);
        }

        [HttpPost]
        public ActionResult EditUser(User user)
        {
            UnitOfWork.AdministrationRepository.Update(UnitOfWork, user);
            return RedirectToAction("Users");
        }

        public ActionResult CreateUser()
        {
            if (!WebSecurity.Initialized)
            {
                WebSecurity.InitializeDatabaseConnection("TicketDataBaseContext", "User", "UserId", "UserName", autoCreateTables: true);
            }
            var user = new CreateUser();
            return PartialView("_createUserPartial", user); 
        }

        [HttpPost]
        public ActionResult CreateUser(CreateUser user)
        {
            UnitOfWork.AdministrationRepository.CreateUser(UnitOfWork, user);
            return RedirectToAction("Users");
        }

    }
}

Ticket.Web/Ticket.Web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticket.Web.DAL.Repository;

namespace Ticket.Web.Controllers
{
    [Authorize]
    public class BaseController : Controller
    {

        private UnitOfWork unitOfWork;
        public UnitOfWork UnitOfWork
        {
            get 
            {
                if (unitOfWork == null)
                {
                    unitOfWork = new UnitOfWork();
                }
                return unitOfWork;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (unitOfWork != null) unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

Ticket.Web/Ticket.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ticket.Web.Controllers
{
    public class HomeController : BaseController
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Ticket.Web/Ticket.Web/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticket.Web.DAL.Repository.Model.Ticket;
namespace Ticket.Web.Controllers
{
    public class TicketController : BaseController
    {
        //
        // GET: /Ticket/

        public ActionResult Tickets()
        {
            var tickets = UnitOfWork.TicketRepository.GetTickets(UnitOfWork);

            return View("Tickets", tickets);
        }

        public ActionResult Create()
        {
            var model = new TicketShortModel();
            var users = UnitOfWork.AdministrationRepository.GetUsers(UnitOfWork);
            ViewData["Users"] = new SelectList(users,"UserId", "UserName");
            
            return View("CreateTicket", model);
        }

        [HttpPost]
        public ActionResult Create(TicketShortModel model)
        {
            UnitOfWork.TicketRepository.Create(UnitOfWork, model);
            UnitOfWork.Context.SaveChanges();
            return RedirectToAction("Tickets");
        }

        public ActionResult Details(int id)
        {
            var ticket = UnitOfWork.TicketRepository.GetTicketDetails(UnitOfWork, id);
            return View("Details", ticket);
        }

        [HttpPost]
        public ActionResult AddComment(int ticketId, string comment)
        {
            UnitOfWork.TicketRepository.CreateCommnet(UnitOfWork, comment, ticketId);
            UnitOfWork.Context.SaveChanges();
            return RedirectToAction("Details", new { id = ticketId });
        }
    }
}

Ticket.Web/Ticket.Web/Views/Administration/Users.cshtml
@using Ticket.Web.DAL.Repository.Model.Administration
@model List<User>

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Users list</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-10"> </div>
                <div class="col-lg-2 text-right " style="margin-bottom: 7px;">
                    <button class="btn btn-default" id="createUser">Create user</button>
                </div>
            </div>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th> Login:</th>
                                <th> First Name:</th>
                                <th> Surname:</th>
                                <th> E-mail:</th>
                                <th> Phone:</th>
                                <th> Action:</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in @Model)
                            {
                                <tr>
                                    <td>@item.UserName</td>
                                    <td>@item.FirstName</td>
                                    <td>@item.Surname</td>
                                    <td>@item.Email</td>
                                    <td>@item.Phone</td>
                                    <td><button class="edit_user btn btn-default" data-id="@item.UserId">Edit</button></td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
    </div>

    <div id="editUser">

    </div>
    <div id="creatUser">

    </div>

    @section scripts
    {
    <script type="text/javascript">

        $(document).ready(function () {
            $('.edit_user').click(function () {
                var id = $(this).attr("data-id");

                $.ajax({
                    url: 'EditUser?userId=' + id,
                    dataType: 'html',
                    type: 'GET',
                    success: function (response) {
                        console.log(response);
                        $('#editUser').html(response);

                        $('#editUserModal').modal();

                    }
                });
            });

            $('#createUser').click(function () {
              
                $.ajax({
                    url: 'CreateUser',
                    dataType: 'html',
                    type: 'GET',
                    success: function (response) {
                        console.log(response);
                        $('#creatUser').html(response);

                        $('#createUserModal').modal();

                    }
                });
            });
        });

    </script>
    }

Ticket.Web/Ticket.Web/Views/Administration/_createUserPartial.cshtml
@using System.Web.Mvc
@model Ticket.Web.DAL.Repository.Model.Administration.CreateUser


<div class="modal fade" id="createUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Create user</h4>
            </div>
            @using (Html.BeginForm("CreateUser", "Administration", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <input type="hidden" name="UserId" value="@Model.UserId" class="form-control" />
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Login:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="UserName" value="@Model.UserName" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">First name:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="FirstName" value="@Model.FirstName" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Surname:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="Surname" value="@Model.Surname" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Email:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="Email" value="@Model.Email" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Password:</label>
                                <div class="col-sm-10">
                                    <input type="password" name="Password" value="@Model.Password" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Confirm password:</label>
                                <div class="col-sm-10">
                                    <input type="password" name="ConfirmPassword" value="@Model.ConfirmPassword" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Phone:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="Phone" value="@Model.Phone" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer ">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            }
        </div>
    </div>
</div>

Ticket.Web/Ticket.Web/Views/Administration/_editUserPartial.cshtml
@using System.Web.Mvc
@model Ticket.Web.DAL.Repository.Model.Administration.User


<div class="modal fade" id="editUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Edycja użytkownika</h4>
            </div>
        @using (Html.BeginForm("EditUser", "Administration", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                     

                            <input type="hidden" name="UserId" value="@Model.UserId" class="form-control" />
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Login:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="UserName" value="@Model.UserName" class="form-control" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">First name:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="FirstName" value="@Model.FirstName" class="form-control" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Surname:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="Surname" value="@Model.Surname" class="form-control" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Email:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="Email" value="@Model.Email" class="form-control" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Phone:</label>
                                <div class="col-sm-10">
                                    <input type="text" name="Phone" value="@Model.Phone" class="form-control" />
                                </div>
                            </div>
                       
                    </div>
                </div>
            </div>
            <div class="modal-footer ">
                <button type="submit" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        }
        </div>
    </div>
</div>

Ticket.Web/Ticket.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Dashboard</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">26</div>
                            <div>New Tickets!</div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <span class="pull-right"></span>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tasks fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">12</div>
                            <div>New Tickets!</div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">

                    <span class="pull-right"></span>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">124</div>
                            <div>New Tickets!</div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <span class="pull-right"></span>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-support fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">13</div>
                            <div>Support Tickets!</div>
                        </div>
                    </div>
                </div>

                <div class="panel-footer">
                    <span class="pull-right"></span>
                    <div class="clearfix"></div>
                </div>

            </div>
        </div>
    </div>

Ticket.Web/Ticket.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/metisMenu.css" rel="stylesheet" />
    <link href="~/Content/timeline.css" rel="stylesheet" />
    <link href="~/Content/sb-admin-2.css" rel="stylesheet" />
    <link href="~/Content/morris.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            @Html.Partial("_navbarLayout")
            @Html.Partial("_navigationLayout")
        </nav>
        <div id="page-wrapper">
            @RenderBody()
        </div>
    </div>
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/metisMenu.js"></script>
    <script src="~/Scripts/raphael-min.js"></script>
    <script src="~/Scripts/sb-admin-2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Ticket.Web/Ticket.Web/Views/Shared/_navigationLayout.cshtml
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                @Html.ActionLink("Dashboard", "Index", "Home")
            </li>
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Administration<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        @Html.ActionLink("Users", "Users","Administration")
                     
                    </li>
               
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i>Tickets<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        @Html.ActionLink("Current tickets", "Tickets", "Ticket") 
                    </li>
                    <li>
                        @Html.ActionLink("Create", "Create", "Ticket")
                    </li>
                </ul>
            </li>
           
        </ul>
    </div>
</div>

Ticket.Web/Ticket.Web/Views/Ticket/CreateTicket.cshtml
@model Ticket.Web.DAL.Repository.Model.Ticket.TicketShortModel

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Create ticket</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Create", "Ticket", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Title:</label>
                <div class="col-sm-10">
                    <input type="text" name="Title" value="@Model.Title" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Description:</label>
                <div class="col-sm-10">
                    <textarea rows="4" cols="50" name="Description" class="form-control"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Status:</label>
                <div class="col-sm-10">
                    <select name="StatusId" class="form-control">
                        <option value="0">Created</option>
                        <option value="1">Opened</option>
                        <option value="2">Resolved</option>
                        <option value="3">Closed</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Priority:</label>
                <div class="col-sm-10">
                    <select name="PriorityId" class="form-control">
                        <option value="0">Critical</option>
                        <option value="1">Major</option>
                        <option value="2">Normal</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Assign to:</label>
                <div class="col-sm-10">
                   @Html.DropDownListFor(m => m.AssignToId, (SelectList)ViewData["Users"], new { @class= "form-control"})
                </div>
            </div>
    <div class="form-group text-center ">
        <button type="submit" class="btn btn-primary">Save </button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
        }
    </div>
</div>

Ticket.Web/Ticket.Web/Views/Ticket/Details.cshtml
@using Ticket.Web.DAL.Repository.Model.Ticket
@model TicketDetailsModel

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Details - @Model.Ticket.Title</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-6">
        <dl class="dl-horizontal">
            <dt>Created date:</dt>
            <dd>@Model.Ticket.DateCreated</dd>
            <dt>Created by user:</dt>
            <dd>@Model.Ticket.CreatedBy</dd>
            <dt>Assign to user:</dt>
            <dd>@Model.Ticket.AssignTo</dd>
        </dl>
    </div>
    <div class="col-lg-6">
        <dl class="dl-horizontal">
            <dt>Status:</dt>
            <dd>@Model.Ticket.Status</dd>
            <dt>Piority:</dt>
            <dd>@Model.Ticket.Priority</dd>
        </dl>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <dl class="dl-horizontal">
            <dt>Description</dt>
            <dd>@Model.Ticket.Description</dd>
        </dl>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
    @foreach (var item in @Model.TicketDisciusions)
    {
        <div class="panel panel-default">
            <div class="panel-heading"> @item.CreatedBy: @item.DateCreate </div>
            <div class="panel-body">
                @item.Description
            </div>
            <div class="panel-footer">  </div>
        </div>
    }
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            @using (Html.BeginForm("AddComment", "Ticket", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="panel-heading">Add Comment </div>
                <div class="panel-body">
                    <input type="hidden" name="TicketId" value="@Model.Ticket.Id" />
                 
                    <textarea rows="4" cols="50" name="Description" class="form-control"></textarea>
                </div>
                <div class="panel-footer text-center">
                    <button class="btn btn-primary" type="submit">Save</button> 
                </div>
            }
        </div>
    </div>
</div>

Ticket.Web/Ticket.Web/Views/Ticket/Tickets.cshtml
@using Ticket.Web.DAL.Repository.Model.Ticket
@model List<TicketShortModel>
  
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Ticket List</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th> Create date:</th>
                            <th> Title:</th>
                            <th> Created by:</th>
                            <th> Assigned to:</th>
                            <th> Status:</th>
                            <th> Priority:</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in @Model)
                        {
                            <tr>
                                <td>@item.DateCreated.ToString("yyyy-MM-dd")</td>
                                <td>@item.Title</td>
                                <td>@item.CreatedBy</td>
                                <td>@item.AssignTo</td>
                                <td>@item.Status.ToString()</td>
                                <td>@item.Priority.ToString()</td>
                                <td><a href="Details?id=@item.Id" class=" btn btn-default" >Details</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>